[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*", "https://api.dicebear.com/.*", "https://placehold.co/.*"]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  SKIP_TYPE_CHECK = "true"
  SKIP_ESLINT = "true"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"
